export const API_URL = 'http://localhost:8888'
export const AUTH_URL = API_URL + '/auth/token'
export const USER_URL = API_URL + '/user'
export const EXPRESSION_URL = API_URL + '/exp'
export const POSTEXP_URL = EXPRESSION_URL + '/exp' + '/calculate'
